# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-22 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_visit_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit_comment',
            old_name='created_time',
            new_name='date',
        ),
    ]
